name: nutrition_app
description: Mobile app for customizing meals and macros.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'  # Актуальная на 2025

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  unicons: ^2.0.5
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  sizer: ^3.0.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1  # Добавлено для SQLite БД (пункт 1 задания)
  path: ^1.9.0  # Для sqflite
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/recipebook.gif

#  fonts:
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat-Regular.ttf  # Добавьте файл в fonts/ если используете локально